spring:
  application:
      name: ai-code-helper
  profiles:
    active: local

langchain4j:
  community:
    dashscope:
      chat-model:
        model-name: qwen-max
        api-key: <You API Key here>
      embedding-model:
        api-key: <You API Key here>
        model-name: text-embedding-v4
